version: "3.9"
services:
  calendar_service:
    build:
      context: ./calendar_service
    ports:
      - "8001:8000"
    volumes:
      - sqlite_calendar_data:/data
    depends_on:
      - analytics_service

  analytics_service:
    build:
      context: ./analytics_service
    ports:
      - "8002:8000"
    volumes:
      - sqlite_analytics_data:/data

volumes:
  sqlite_calendar_data:
  sqlite_analytics_data:
